class AminoAcid {
    // Create a protein from three nucleotides.
    constructor(n1, n2, n3) {
        this.codon = n1+n2+n3
        this.value = AminoAcid.codonMap[this.codon]
    }
}

AminoAcid.codonMap = {
    'TAA': 'STOP',
    'TGA': 'STOP',
    'TAG': 'STOP',
    'GTT': 'Val',
    'GTC': 'Val',
    'GTA': 'Val',
    'GTG': 'Val',
    'TAT': 'Tyr',
    'TAC': 'Tyr',
    'TGG': 'Trp',
    'ACT': 'Thr',
    'ACC': 'Thr',
    'ACA': 'Thr',
    'ACG': 'Thr',
    'TCT': 'Ser',
    'TCC': 'Ser',
    'TCA': 'Ser',
    'TCG': 'Ser',
    'AGT': 'Ser',
    'AGC': 'Ser',
    'CCT': 'Pro',
    'CCC': 'Pro',
    'CCA': 'Pro',
    'CCG': 'Pro',
    'TTT': 'Phe',
    'TTC': 'Phe',
    'ATG': 'Met',
    'AAA': 'Lys',
    'AAG': 'Lys',
    'CTT': 'Leu',
    'CTC': 'Leu',
    'CTA': 'Leu',
    'CTG': 'Leu',
    'TTA': 'Leu',
    'TTG': 'Leu',
    'ATT': 'Ile',
    'ATC': 'Ile',
    'ATA': 'Ile',
    'CAT': 'His',
    'CAC': 'His',
    'GGT': 'Gly',
    'GGC': 'Gly',
    'GGA': 'Gly',
    'GGG': 'Gly',
    'GAA': 'Glu',
    'GAG': 'Glu',
    'CAA': 'Gln',
    'CAG': 'Gln',
    'TGT': 'Cys',
    'TGC': 'Cys',
    'GAT': 'Asp',
    'GAC': 'Asp',
    'AAT': 'Asn',
    'AAC': 'Asn',
    'CGT': 'Arg',
    'CGC': 'Arg',
    'CGA': 'Arg',
    'CGG': 'Arg',
    'AGA': 'Arg',
    'AGG': 'Arg',
    'GCT': 'Ala',
    'GCC': 'Ala',
    'GCA': 'Ala',
    'GCG': 'Ala',
}

export default AminoAcid
